### ISSUE TITLE
Image upload does not work

### ISSUE THREAD

**Issue by waptik** [andreaskeller/react-cloudinary#1]
Hi! I found your blogpost on twitter and tried out the demo. But whilst uploading an image, i found out that `NEXT_PUBLIC_CLOUDINARY_CLOUDNAME` isn't defined making the upload not to work.
Looking at network traffic in devtools, the upload is https://api.cloudinary.com/v1_1/undefined/upload instead of a proper one.
It might be you didn't define the environment variable `NEXT_PUBLIC_CLOUDINARY_CLOUDNAME` on vercel or something went wrong.
Anyway, i just wanted to let you know.
Have a nice day!

**Comment by andreaskeller** [comment]
Hi, thanks for letting me know! Indeed I forgot to set the environment variables. I added them and now everything you should work. Thanks again!

**Comment by waptik** [comment]
All good now!
